twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
       contact_adresse: '12 rue du village'
       contact_zip: '12345'
       contact_city: 'ville'
       contact_phone: '01 23 45 67 89'
       contact_email: 'prenom.nom@domaine.fr'
       copyright: 'Copyright ©️ 2021 Manel BENALI'

when@test:
    twig:
        strict_variables: true
